
/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/

module PersonalFinance.Models {

	 export type IRole = "PublicUser" | "GroupMember" | "GroupAdmin" | "AnonymousOverPrivateApi" | "SystemAdministrator";
	 export type IBudgetType = "Savings" | "Spendings";
	 export type IBudgetItemType = "Expense" | "Income";
	 export type IPaymentFrequency = "Daily" | "Weekly" | "Fortnightly" | "Monthly" | "Yearly";


	 export const Role = {
		 PublicUser: "PublicUser" as IRole,
		 GroupMember: "GroupMember" as IRole,
		 GroupAdmin: "GroupAdmin" as IRole,
		 AnonymousOverPrivateApi: "AnonymousOverPrivateApi" as IRole,
		 SystemAdministrator: "SystemAdministrator" as IRole,
	 }
	 export const BudgetType = {
		 Savings: "Savings" as IBudgetType,
		 Spendings: "Spendings" as IBudgetType,
	 }
	 export const BudgetItemType = {
		 Expense: "Expense" as IBudgetItemType,
		 Income: "Income" as IBudgetItemType,
	 }
	 export const PaymentFrequency = {
		 Daily: "Daily" as IPaymentFrequency,
		 Weekly: "Weekly" as IPaymentFrequency,
		 Fortnightly: "Fortnightly" as IPaymentFrequency,
		 Monthly: "Monthly" as IPaymentFrequency,
		 Yearly: "Yearly" as IPaymentFrequency,
	 }
	export const EnumLabelDictionary = {
		"RolePublicUser":"PublicUser",
		"RoleGroupMember":"GroupMember",
		"RoleGroupAdmin":"GroupAdmin",
		"RoleAnonymousOverPrivateApi":"AnonymousOverPrivateApi",
		"RoleSystemAdministrator":"SystemAdministrator",
		"BudgetTypeSavings":"Savings",
		"BudgetTypeSpendings":"Spendings",
		"BudgetItemTypeExpense":"Expense",
		"BudgetItemTypeIncome":"Income",
		"PaymentFrequencyDaily":"Daily",
		"PaymentFrequencyWeekly":"Weekly",
		"PaymentFrequencyFortnightly":"Fortnightly",
		"PaymentFrequencyMonthly":"Monthly",
		"PaymentFrequencyYearly":"Yearly",
		get: function(type, key) {
			return this[type + key];
		}
	}
}


