
/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/

module PersonalFinance.Models {

	 export type IRole = "PublicUser" | "HouseholdMember" | "HouseholdAdmin" | "AnonymousOverPrivateApi" | "SystemAdministrator";
	 export type IBudgetType = "Savings" | "Spendings";
	 export type IBudgetItemType = "Expense" | "Income";


	 export const Role = {
		 PublicUser: "PublicUser" as IRole,
		 HouseholdMember: "HouseholdMember" as IRole,
		 HouseholdAdmin: "HouseholdAdmin" as IRole,
		 AnonymousOverPrivateApi: "AnonymousOverPrivateApi" as IRole,
		 SystemAdministrator: "SystemAdministrator" as IRole,
	 }
	 export const BudgetType = {
		 Savings: "Savings" as IBudgetType,
		 Spendings: "Spendings" as IBudgetType,
	 }
	 export const BudgetItemType = {
		 Expense: "Expense" as IBudgetItemType,
		 Income: "Income" as IBudgetItemType,
	 }
	export const EnumLabelDictionary = {
		"RolePublicUser":"PublicUser",
		"RoleHouseholdMember":"HouseholdMember",
		"RoleHouseholdAdmin":"HouseholdAdmin",
		"RoleAnonymousOverPrivateApi":"AnonymousOverPrivateApi",
		"RoleSystemAdministrator":"SystemAdministrator",
		"BudgetTypeSavings":"Savings",
		"BudgetTypeSpendings":"Spendings",
		"BudgetItemTypeExpense":"Expense",
		"BudgetItemTypeIncome":"Income",
		get: function(type, key) {
			return this[type + key];
		}
	}
}


