/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/
var PersonalFinance;
(function (PersonalFinance) {
    var Models;
    (function (Models) {
        Models.Role = {
            PublicUser: "PublicUser",
            HouseholdMember: "HouseholdMember",
            HouseholdAdmin: "HouseholdAdmin",
            AnonymousOverPrivateApi: "AnonymousOverPrivateApi",
            SystemAdministrator: "SystemAdministrator",
        };
        Models.BudgetType = {
            Savings: "Savings",
            Spendings: "Spendings",
        };
        Models.BudgetItemType = {
            Expense: "Expense",
            Income: "Income",
        };
        Models.EnumLabelDictionary = {
            "RolePublicUser": "PublicUser",
            "RoleHouseholdMember": "HouseholdMember",
            "RoleHouseholdAdmin": "HouseholdAdmin",
            "RoleAnonymousOverPrivateApi": "AnonymousOverPrivateApi",
            "RoleSystemAdministrator": "SystemAdministrator",
            "BudgetTypeSavings": "Savings",
            "BudgetTypeSpendings": "Spendings",
            "BudgetItemTypeExpense": "Expense",
            "BudgetItemTypeIncome": "Income",
            get: function (type, key) {
                return this[type + key];
            }
        };
    })(Models = PersonalFinance.Models || (PersonalFinance.Models = {}));
})(PersonalFinance || (PersonalFinance = {}));
//# sourceMappingURL=Enums.js.map