/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/
var PersonalFinance;
(function (PersonalFinance) {
    var Models;
    (function (Models) {
        Models.Role = {
            PublicUser: "PublicUser",
            GroupMember: "GroupMember",
            GroupAdmin: "GroupAdmin",
            AnonymousOverPrivateApi: "AnonymousOverPrivateApi",
            SystemAdministrator: "SystemAdministrator",
        };
        Models.BudgetType = {
            Savings: "Savings",
            Spendings: "Spendings",
        };
        Models.BudgetItemType = {
            Expense: "Expense",
            Income: "Income",
        };
        Models.PaymentFrequency = {
            Daily: "Daily",
            Weekly: "Weekly",
            Fortnightly: "Fortnightly",
            Monthly: "Monthly",
            Yearly: "Yearly",
        };
        Models.EnumLabelDictionary = {
            "RolePublicUser": "PublicUser",
            "RoleGroupMember": "GroupMember",
            "RoleGroupAdmin": "GroupAdmin",
            "RoleAnonymousOverPrivateApi": "AnonymousOverPrivateApi",
            "RoleSystemAdministrator": "SystemAdministrator",
            "BudgetTypeSavings": "Savings",
            "BudgetTypeSpendings": "Spendings",
            "BudgetItemTypeExpense": "Expense",
            "BudgetItemTypeIncome": "Income",
            "PaymentFrequencyDaily": "Daily",
            "PaymentFrequencyWeekly": "Weekly",
            "PaymentFrequencyFortnightly": "Fortnightly",
            "PaymentFrequencyMonthly": "Monthly",
            "PaymentFrequencyYearly": "Yearly",
            get: function (type, key) {
                return this[type + key];
            }
        };
    })(Models = PersonalFinance.Models || (PersonalFinance.Models = {}));
})(PersonalFinance || (PersonalFinance = {}));
//# sourceMappingURL=Enums.js.map