
/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/

module PersonalFinance.Models {

	 export type IRole = "PublicUser" | "HouseholdMember" | "HouseholdAdmin" | "AnonymousOverPrivateApi" | "SystemAdministrator";


	 export const Role = {
		 PublicUser: "PublicUser" as IRole,
		 HouseholdMember: "HouseholdMember" as IRole,
		 HouseholdAdmin: "HouseholdAdmin" as IRole,
		 AnonymousOverPrivateApi: "AnonymousOverPrivateApi" as IRole,
		 SystemAdministrator: "SystemAdministrator" as IRole,
	 }
	export const EnumLabelDictionary = {
		"RolePublicUser":"PublicUser",
		"RoleHouseholdMember":"HouseholdMember",
		"RoleHouseholdAdmin":"HouseholdAdmin",
		"RoleAnonymousOverPrivateApi":"AnonymousOverPrivateApi",
		"RoleSystemAdministrator":"SystemAdministrator",
		get: function(type, key) {
			return this[type + key];
		}
	}
}


