
/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module PersonalFinance.Models {
    /** Generated from PersonalFinance.PublicWeb.Models.PublicSettings **/
    export interface IPublicSettings {
        buildVersion: string;
        environment: string;
        authClientId: string;
    }
    /** Generated from PersonalFinance.PublicWeb.Models.UserAccount **/
    export interface IUserAccount {
        provider: string;
        externalAccessToken: string;
        userName: string;
        name: string;
        email: string;
        password: string;
        confirmPassword: string;
        role: any;
    }
    /** Generated from PersonalFinance.PrivateWeb.Models.UserDetails **/
    export interface IUserDetails {
        id: number;
        displayName: string;
        email: string;
        roles: any[];
        isAnonymous: boolean;
        isPrivateApiClient: boolean;
        ipAddress: string;
        isSystemAdmin: boolean;
    }
    /** Generated from PersonalFinance.Common.Dtos.BudgetDetailsResponse **/
    export interface IBudgetDetailsResponse {
        budget: PersonalFinance.Models.IBudget;
        budgetItems: PersonalFinance.Models.IBudgetItem[];
    }
    /** Generated from PersonalFinance.Common.Dtos.CreateGroupRequest **/
    export interface ICreateGroupRequest {
        name: string;
    }
    /** Generated from PersonalFinance.Common.Dtos.GroupInviteRequest **/
    export interface IGroupInviteRequest {
        groupId: number;
        toUserEmail: string;
        inviteMessage: string;
        inviteRole: any;
    }
    /** Generated from PersonalFinance.Common.Dtos.LoginRequest **/
    export interface ILoginRequest {
        userName: string;
        password: string;
    }
    /** Generated from PersonalFinance.Common.Dtos.RecentBudgetResponse **/
    export interface IRecentBudgetResponse {
        budget: PersonalFinance.Models.IBudget;
        items: PersonalFinance.Models.IBudgetItem[];
    }
    /** Generated from PersonalFinance.Common.Model.Bill **/
    export interface IBill {
    }
    /** Generated from PersonalFinance.Common.Model.Budget **/
    export interface IBudget {
    }
    /** Generated from PersonalFinance.Common.Model.BudgetItem **/
    export interface IBudgetItem {
    }
    /** Generated from PersonalFinance.Common.Model.Category **/
    export interface ICategory {
    }
    /** Generated from PersonalFinance.Common.Model.Bill **/
    export interface IBill {
        id: number;
        userId: number;
        groupId: number;
        name: string;
        description: string;
        dueDate: string;
        amount: number;
        annualFrequency: number;
        status: string;
    }
    /** Generated from PersonalFinance.Common.Model.BudgetItem **/
    export interface IBudgetItem {
        id: number;
        budgetId: number;
        type: string;
        name: string;
        description: string;
        amount: number;
    }
    /** Generated from PersonalFinance.Common.Model.Budget **/
    export interface IBudget {
        id: number;
        userId: number;
        groupId: number;
        name: string;
        type: string;
        allocatedAmount: number;
        balance: number;
        createdBy: string;
        createdTime: string;
        modifiedBy: string;
        modifiedTime: string;
    }
    /** Generated from PersonalFinance.Common.Model.GroupInvite **/
    export interface IGroupInvite {
        id: number;
        fromUserId: number;
        toUserId: number;
        groupId: number;
        pending: boolean;
        accepted: boolean;
        dateSent: string;
        dateAccepted: string;
    }
    /** Generated from PersonalFinance.Common.Model.GroupMember **/
    export interface IGroupMember {
        id: number;
        userId: number;
        groupId: number;
        role: string;
    }
    /** Generated from PersonalFinance.Common.Model.Group **/
    export interface IGroup {
        id: number;
        name: string;
    }
    /** Generated from PersonalFinance.Common.Model.UserRole **/
    export interface IUserRole {
        id: number;
        userId: number;
        role: string;
    }
    /** Generated from PersonalFinance.Common.Model.User **/
    export interface IUser {
        id: number;
        userName: string;
        name: string;
        email: string;
        phoneNumber: string;
        passwordHash: string;
        createdBy: string;
        createdTime: string;
        modifiedBy: string;
        modifiedTime: string;
    }
    /** Generated from PersonalFinance.Common.Model.Group **/
    export interface IGroup {
    }
    /** Generated from PersonalFinance.Common.Model.GroupInvite **/
    export interface IGroupInvite {
    }
    /** Generated from PersonalFinance.Common.Model.GroupMember **/
    export interface IGroupMember {
    }
    /** Generated from PersonalFinance.Common.Model.PagingFilter **/
    export interface IPagingFilter {
        disablePaging: boolean;
        page: number;
        pageSize: number;
        totalItems: number;
        orderColumn: string;
        orderDirection: any;
    }
    /** Generated from PersonalFinance.Common.Model.PendingInvites **/
    export interface IPendingInvites {
        toEmail: string;
        dateSent: string;
    }
    /** Generated from PersonalFinance.Common.Model.Transaction **/
    export interface ITransaction {
    }
    /** Generated from PersonalFinance.Common.Model.User **/
    export interface IUser {
        userRoles: PersonalFinance.Models.IUserRole[];
    }
    /** Generated from PersonalFinance.Common.Model.UserRole **/
    export interface IUserRole {
    }
}




